---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	business_analyst(business_analyst)
	supervisor(supervisor)
	communicator(communicator)
	content_strategist(content_strategist)
	outline_reviewer(outline_reviewer)
	vector_search_agent(vector_search_agent)
	web_search_agent(web_search_agent)
	__end__([<p>__end__</p>]):::last
	__start__ --> business_analyst;
	business_analyst --> supervisor;
	content_strategist --> outline_reviewer;
	outline_reviewer --> business_analyst;
	supervisor -.-> communicator;
	supervisor -.-> content_strategist;
	supervisor -.-> vector_search_agent;
	supervisor -.-> web_search_agent;
	vector_search_agent --> business_analyst;
	web_search_agent --> vector_search_agent;
	communicator --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
